---

    - name: Configure /etc/udev/rules.d/70-persistent-net.rules
      template:
        src: 70-persistent-net.rules.j2
        dest: /etc/udev/rules.d/70-persistent-net.rules
      notify:
        - Reload udev rules again




    - name: Install
      apt:
        name:
          - hostapd
          - dnsmasq
          - iw
          - openvpn
          - iptables-persistent
          - unzip
          - dkms
        state: present
        update_cache: yes
      become: yes



    - name: Configure /etc/netplan/50-cloud-init.yaml
      template:
        src: 50-cloud-init.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml



    - name: Coppy CFG
      copy:
        src: "{{VPN_CFG}}"
        dest: "/etc/openvpn/{{VPN_CFG}}"





    - name: /etc/openvpn/auth.txt
      template:
        src: auth.txt.j2
        dest: /etc/openvpn/auth.txt

    - name:  auth
      command: sed -i.bak 's/^auth-user-pass/auth-user-pass \/etc\/openvpn\/auth.txt/' /etc/openvpn/{{VPN_CFG}}

    - name: Configure OpenVPN
      template:
        src: openvpn-surfshark.service.j2
        dest: /etc/systemd/system/openvpn-surfshark.service
    - name: Reload daemon
      systemd:
        daemon_reload: yes


    - name: Enable VPN
      systemd:
        name: openvpn-surfshark.service
        enabled: true

    - name: Restart VPN
      systemd:
        name: openvpn-surfshark.service
        state: restarted


    - name: Configure Hostapd
      template:
        src: hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
      notify:
        - Restart hostapd
    - name: Unmask hostapd service
      command: systemctl unmask hostapd.service



    - name: Stop systemd-resolved
      service:
        name: systemd-resolved
        state: stopped

    - name: Disable systemd-resolved
      service:
        name: systemd-resolved
        enabled: false









    - name: Configure dnsmasq
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
      notify:
        - Restart dnsmasq


    - name: Enable IP forwarding
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward=1"
        state: present

    - name: Apply sysctl changes
      command: sysctl -p


    - name: Configure iptables for NAT
      command: iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
      args:

    - name: Save iptables rules
      command: netfilter-persistent save
      args:
